// @generated by buffa-codegen. DO NOT EDIT.
// source: obs/v1/options.proto

///Extension `event` on `.google.protobuf.MessageOptions` (field 80001).
pub const EVENT: ::buffa::Extension<
    ::buffa::extension::codecs::MessageCodec<super::super::EventMeta>,
> = ::buffa::Extension::new(80001u32, "google.protobuf.MessageOptions");
///Extension `field` on `.google.protobuf.FieldOptions` (field 80002).
pub const FIELD: ::buffa::Extension<
    ::buffa::extension::codecs::MessageCodec<super::super::FieldMeta>,
> = ::buffa::Extension::new(80002u32, "google.protobuf.FieldOptions");
