// @generated by buffa-codegen. DO NOT EDIT.
// source: obs/v1/enums.proto

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(i32)]
pub enum Tier {
    TIER_UNSPECIFIED = 0i32,
    TIER_LOG = 1i32,
    TIER_METRIC = 2i32,
    TIER_TRACE = 3i32,
    TIER_AUDIT = 4i32,
}
impl ::core::default::Default for Tier {
    fn default() -> Self {
        Self::TIER_UNSPECIFIED
    }
}
impl ::buffa::Enumeration for Tier {
    fn from_i32(value: i32) -> ::core::option::Option<Self> {
        match value {
            0i32 => ::core::option::Option::Some(Self::TIER_UNSPECIFIED),
            1i32 => ::core::option::Option::Some(Self::TIER_LOG),
            2i32 => ::core::option::Option::Some(Self::TIER_METRIC),
            3i32 => ::core::option::Option::Some(Self::TIER_TRACE),
            4i32 => ::core::option::Option::Some(Self::TIER_AUDIT),
            _ => ::core::option::Option::None,
        }
    }
    fn to_i32(&self) -> i32 {
        *self as i32
    }
    fn proto_name(&self) -> &'static str {
        match self {
            Self::TIER_UNSPECIFIED => "TIER_UNSPECIFIED",
            Self::TIER_LOG => "TIER_LOG",
            Self::TIER_METRIC => "TIER_METRIC",
            Self::TIER_TRACE => "TIER_TRACE",
            Self::TIER_AUDIT => "TIER_AUDIT",
        }
    }
    fn from_proto_name(name: &str) -> ::core::option::Option<Self> {
        match name {
            "TIER_UNSPECIFIED" => ::core::option::Option::Some(Self::TIER_UNSPECIFIED),
            "TIER_LOG" => ::core::option::Option::Some(Self::TIER_LOG),
            "TIER_METRIC" => ::core::option::Option::Some(Self::TIER_METRIC),
            "TIER_TRACE" => ::core::option::Option::Some(Self::TIER_TRACE),
            "TIER_AUDIT" => ::core::option::Option::Some(Self::TIER_AUDIT),
            _ => ::core::option::Option::None,
        }
    }
    fn values() -> &'static [Self] {
        &[
            Self::TIER_UNSPECIFIED,
            Self::TIER_LOG,
            Self::TIER_METRIC,
            Self::TIER_TRACE,
            Self::TIER_AUDIT,
        ]
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(i32)]
pub enum Severity {
    SEVERITY_UNSPECIFIED = 0i32,
    SEVERITY_TRACE = 1i32,
    SEVERITY_DEBUG = 2i32,
    SEVERITY_INFO = 3i32,
    SEVERITY_WARN = 4i32,
    SEVERITY_ERROR = 5i32,
    SEVERITY_FATAL = 6i32,
}
impl ::core::default::Default for Severity {
    fn default() -> Self {
        Self::SEVERITY_UNSPECIFIED
    }
}
impl ::buffa::Enumeration for Severity {
    fn from_i32(value: i32) -> ::core::option::Option<Self> {
        match value {
            0i32 => ::core::option::Option::Some(Self::SEVERITY_UNSPECIFIED),
            1i32 => ::core::option::Option::Some(Self::SEVERITY_TRACE),
            2i32 => ::core::option::Option::Some(Self::SEVERITY_DEBUG),
            3i32 => ::core::option::Option::Some(Self::SEVERITY_INFO),
            4i32 => ::core::option::Option::Some(Self::SEVERITY_WARN),
            5i32 => ::core::option::Option::Some(Self::SEVERITY_ERROR),
            6i32 => ::core::option::Option::Some(Self::SEVERITY_FATAL),
            _ => ::core::option::Option::None,
        }
    }
    fn to_i32(&self) -> i32 {
        *self as i32
    }
    fn proto_name(&self) -> &'static str {
        match self {
            Self::SEVERITY_UNSPECIFIED => "SEVERITY_UNSPECIFIED",
            Self::SEVERITY_TRACE => "SEVERITY_TRACE",
            Self::SEVERITY_DEBUG => "SEVERITY_DEBUG",
            Self::SEVERITY_INFO => "SEVERITY_INFO",
            Self::SEVERITY_WARN => "SEVERITY_WARN",
            Self::SEVERITY_ERROR => "SEVERITY_ERROR",
            Self::SEVERITY_FATAL => "SEVERITY_FATAL",
        }
    }
    fn from_proto_name(name: &str) -> ::core::option::Option<Self> {
        match name {
            "SEVERITY_UNSPECIFIED" => {
                ::core::option::Option::Some(Self::SEVERITY_UNSPECIFIED)
            }
            "SEVERITY_TRACE" => ::core::option::Option::Some(Self::SEVERITY_TRACE),
            "SEVERITY_DEBUG" => ::core::option::Option::Some(Self::SEVERITY_DEBUG),
            "SEVERITY_INFO" => ::core::option::Option::Some(Self::SEVERITY_INFO),
            "SEVERITY_WARN" => ::core::option::Option::Some(Self::SEVERITY_WARN),
            "SEVERITY_ERROR" => ::core::option::Option::Some(Self::SEVERITY_ERROR),
            "SEVERITY_FATAL" => ::core::option::Option::Some(Self::SEVERITY_FATAL),
            _ => ::core::option::Option::None,
        }
    }
    fn values() -> &'static [Self] {
        &[
            Self::SEVERITY_UNSPECIFIED,
            Self::SEVERITY_TRACE,
            Self::SEVERITY_DEBUG,
            Self::SEVERITY_INFO,
            Self::SEVERITY_WARN,
            Self::SEVERITY_ERROR,
            Self::SEVERITY_FATAL,
        ]
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(i32)]
pub enum FieldKind {
    FIELD_KIND_UNSPECIFIED = 0i32,
    LABEL = 1i32,
    ATTRIBUTE = 2i32,
    MEASUREMENT = 3i32,
    TRACE_ID = 4i32,
    SPAN_ID = 5i32,
    PARENT_SPAN_ID = 6i32,
    TIMESTAMP_NS = 7i32,
    DURATION_NS = 8i32,
    FORENSIC = 9i32,
}
impl ::core::default::Default for FieldKind {
    fn default() -> Self {
        Self::FIELD_KIND_UNSPECIFIED
    }
}
impl ::buffa::Enumeration for FieldKind {
    fn from_i32(value: i32) -> ::core::option::Option<Self> {
        match value {
            0i32 => ::core::option::Option::Some(Self::FIELD_KIND_UNSPECIFIED),
            1i32 => ::core::option::Option::Some(Self::LABEL),
            2i32 => ::core::option::Option::Some(Self::ATTRIBUTE),
            3i32 => ::core::option::Option::Some(Self::MEASUREMENT),
            4i32 => ::core::option::Option::Some(Self::TRACE_ID),
            5i32 => ::core::option::Option::Some(Self::SPAN_ID),
            6i32 => ::core::option::Option::Some(Self::PARENT_SPAN_ID),
            7i32 => ::core::option::Option::Some(Self::TIMESTAMP_NS),
            8i32 => ::core::option::Option::Some(Self::DURATION_NS),
            9i32 => ::core::option::Option::Some(Self::FORENSIC),
            _ => ::core::option::Option::None,
        }
    }
    fn to_i32(&self) -> i32 {
        *self as i32
    }
    fn proto_name(&self) -> &'static str {
        match self {
            Self::FIELD_KIND_UNSPECIFIED => "FIELD_KIND_UNSPECIFIED",
            Self::LABEL => "LABEL",
            Self::ATTRIBUTE => "ATTRIBUTE",
            Self::MEASUREMENT => "MEASUREMENT",
            Self::TRACE_ID => "TRACE_ID",
            Self::SPAN_ID => "SPAN_ID",
            Self::PARENT_SPAN_ID => "PARENT_SPAN_ID",
            Self::TIMESTAMP_NS => "TIMESTAMP_NS",
            Self::DURATION_NS => "DURATION_NS",
            Self::FORENSIC => "FORENSIC",
        }
    }
    fn from_proto_name(name: &str) -> ::core::option::Option<Self> {
        match name {
            "FIELD_KIND_UNSPECIFIED" => {
                ::core::option::Option::Some(Self::FIELD_KIND_UNSPECIFIED)
            }
            "LABEL" => ::core::option::Option::Some(Self::LABEL),
            "ATTRIBUTE" => ::core::option::Option::Some(Self::ATTRIBUTE),
            "MEASUREMENT" => ::core::option::Option::Some(Self::MEASUREMENT),
            "TRACE_ID" => ::core::option::Option::Some(Self::TRACE_ID),
            "SPAN_ID" => ::core::option::Option::Some(Self::SPAN_ID),
            "PARENT_SPAN_ID" => ::core::option::Option::Some(Self::PARENT_SPAN_ID),
            "TIMESTAMP_NS" => ::core::option::Option::Some(Self::TIMESTAMP_NS),
            "DURATION_NS" => ::core::option::Option::Some(Self::DURATION_NS),
            "FORENSIC" => ::core::option::Option::Some(Self::FORENSIC),
            _ => ::core::option::Option::None,
        }
    }
    fn values() -> &'static [Self] {
        &[
            Self::FIELD_KIND_UNSPECIFIED,
            Self::LABEL,
            Self::ATTRIBUTE,
            Self::MEASUREMENT,
            Self::TRACE_ID,
            Self::SPAN_ID,
            Self::PARENT_SPAN_ID,
            Self::TIMESTAMP_NS,
            Self::DURATION_NS,
            Self::FORENSIC,
        ]
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(i32)]
pub enum Cardinality {
    CARDINALITY_UNSPECIFIED = 0i32,
    LOW = 1i32,
    MEDIUM = 2i32,
    HIGH = 3i32,
    UNBOUNDED = 4i32,
}
impl ::core::default::Default for Cardinality {
    fn default() -> Self {
        Self::CARDINALITY_UNSPECIFIED
    }
}
impl ::buffa::Enumeration for Cardinality {
    fn from_i32(value: i32) -> ::core::option::Option<Self> {
        match value {
            0i32 => ::core::option::Option::Some(Self::CARDINALITY_UNSPECIFIED),
            1i32 => ::core::option::Option::Some(Self::LOW),
            2i32 => ::core::option::Option::Some(Self::MEDIUM),
            3i32 => ::core::option::Option::Some(Self::HIGH),
            4i32 => ::core::option::Option::Some(Self::UNBOUNDED),
            _ => ::core::option::Option::None,
        }
    }
    fn to_i32(&self) -> i32 {
        *self as i32
    }
    fn proto_name(&self) -> &'static str {
        match self {
            Self::CARDINALITY_UNSPECIFIED => "CARDINALITY_UNSPECIFIED",
            Self::LOW => "LOW",
            Self::MEDIUM => "MEDIUM",
            Self::HIGH => "HIGH",
            Self::UNBOUNDED => "UNBOUNDED",
        }
    }
    fn from_proto_name(name: &str) -> ::core::option::Option<Self> {
        match name {
            "CARDINALITY_UNSPECIFIED" => {
                ::core::option::Option::Some(Self::CARDINALITY_UNSPECIFIED)
            }
            "LOW" => ::core::option::Option::Some(Self::LOW),
            "MEDIUM" => ::core::option::Option::Some(Self::MEDIUM),
            "HIGH" => ::core::option::Option::Some(Self::HIGH),
            "UNBOUNDED" => ::core::option::Option::Some(Self::UNBOUNDED),
            _ => ::core::option::Option::None,
        }
    }
    fn values() -> &'static [Self] {
        &[
            Self::CARDINALITY_UNSPECIFIED,
            Self::LOW,
            Self::MEDIUM,
            Self::HIGH,
            Self::UNBOUNDED,
        ]
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(i32)]
pub enum Classification {
    CLASSIFICATION_UNSPECIFIED = 0i32,
    INTERNAL = 1i32,
    PII = 2i32,
    SECRET = 3i32,
}
impl ::core::default::Default for Classification {
    fn default() -> Self {
        Self::CLASSIFICATION_UNSPECIFIED
    }
}
impl ::buffa::Enumeration for Classification {
    fn from_i32(value: i32) -> ::core::option::Option<Self> {
        match value {
            0i32 => ::core::option::Option::Some(Self::CLASSIFICATION_UNSPECIFIED),
            1i32 => ::core::option::Option::Some(Self::INTERNAL),
            2i32 => ::core::option::Option::Some(Self::PII),
            3i32 => ::core::option::Option::Some(Self::SECRET),
            _ => ::core::option::Option::None,
        }
    }
    fn to_i32(&self) -> i32 {
        *self as i32
    }
    fn proto_name(&self) -> &'static str {
        match self {
            Self::CLASSIFICATION_UNSPECIFIED => "CLASSIFICATION_UNSPECIFIED",
            Self::INTERNAL => "INTERNAL",
            Self::PII => "PII",
            Self::SECRET => "SECRET",
        }
    }
    fn from_proto_name(name: &str) -> ::core::option::Option<Self> {
        match name {
            "CLASSIFICATION_UNSPECIFIED" => {
                ::core::option::Option::Some(Self::CLASSIFICATION_UNSPECIFIED)
            }
            "INTERNAL" => ::core::option::Option::Some(Self::INTERNAL),
            "PII" => ::core::option::Option::Some(Self::PII),
            "SECRET" => ::core::option::Option::Some(Self::SECRET),
            _ => ::core::option::Option::None,
        }
    }
    fn values() -> &'static [Self] {
        &[Self::CLASSIFICATION_UNSPECIFIED, Self::INTERNAL, Self::PII, Self::SECRET]
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(i32)]
pub enum MetricKind {
    METRIC_KIND_UNSPECIFIED = 0i32,
    METRIC_KIND_COUNTER = 1i32,
    METRIC_KIND_GAUGE = 2i32,
    METRIC_KIND_HISTOGRAM = 3i32,
}
impl ::core::default::Default for MetricKind {
    fn default() -> Self {
        Self::METRIC_KIND_UNSPECIFIED
    }
}
impl ::buffa::Enumeration for MetricKind {
    fn from_i32(value: i32) -> ::core::option::Option<Self> {
        match value {
            0i32 => ::core::option::Option::Some(Self::METRIC_KIND_UNSPECIFIED),
            1i32 => ::core::option::Option::Some(Self::METRIC_KIND_COUNTER),
            2i32 => ::core::option::Option::Some(Self::METRIC_KIND_GAUGE),
            3i32 => ::core::option::Option::Some(Self::METRIC_KIND_HISTOGRAM),
            _ => ::core::option::Option::None,
        }
    }
    fn to_i32(&self) -> i32 {
        *self as i32
    }
    fn proto_name(&self) -> &'static str {
        match self {
            Self::METRIC_KIND_UNSPECIFIED => "METRIC_KIND_UNSPECIFIED",
            Self::METRIC_KIND_COUNTER => "METRIC_KIND_COUNTER",
            Self::METRIC_KIND_GAUGE => "METRIC_KIND_GAUGE",
            Self::METRIC_KIND_HISTOGRAM => "METRIC_KIND_HISTOGRAM",
        }
    }
    fn from_proto_name(name: &str) -> ::core::option::Option<Self> {
        match name {
            "METRIC_KIND_UNSPECIFIED" => {
                ::core::option::Option::Some(Self::METRIC_KIND_UNSPECIFIED)
            }
            "METRIC_KIND_COUNTER" => {
                ::core::option::Option::Some(Self::METRIC_KIND_COUNTER)
            }
            "METRIC_KIND_GAUGE" => ::core::option::Option::Some(Self::METRIC_KIND_GAUGE),
            "METRIC_KIND_HISTOGRAM" => {
                ::core::option::Option::Some(Self::METRIC_KIND_HISTOGRAM)
            }
            _ => ::core::option::Option::None,
        }
    }
    fn values() -> &'static [Self] {
        &[
            Self::METRIC_KIND_UNSPECIFIED,
            Self::METRIC_KIND_COUNTER,
            Self::METRIC_KIND_GAUGE,
            Self::METRIC_KIND_HISTOGRAM,
        ]
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(i32)]
pub enum SamplingReason {
    SAMPLING_REASON_UNSPECIFIED = 0i32,
    SAMPLING_REASON_HEAD_RATE = 1i32,
    SAMPLING_REASON_TAIL_ERROR = 2i32,
    SAMPLING_REASON_SLOW = 3i32,
    SAMPLING_REASON_FORENSIC = 4i32,
    SAMPLING_REASON_AUDIT = 5i32,
    SAMPLING_REASON_RUNTIME = 6i32,
    SAMPLING_REASON_OVERRIDE = 7i32,
}
impl ::core::default::Default for SamplingReason {
    fn default() -> Self {
        Self::SAMPLING_REASON_UNSPECIFIED
    }
}
impl ::buffa::Enumeration for SamplingReason {
    fn from_i32(value: i32) -> ::core::option::Option<Self> {
        match value {
            0i32 => ::core::option::Option::Some(Self::SAMPLING_REASON_UNSPECIFIED),
            1i32 => ::core::option::Option::Some(Self::SAMPLING_REASON_HEAD_RATE),
            2i32 => ::core::option::Option::Some(Self::SAMPLING_REASON_TAIL_ERROR),
            3i32 => ::core::option::Option::Some(Self::SAMPLING_REASON_SLOW),
            4i32 => ::core::option::Option::Some(Self::SAMPLING_REASON_FORENSIC),
            5i32 => ::core::option::Option::Some(Self::SAMPLING_REASON_AUDIT),
            6i32 => ::core::option::Option::Some(Self::SAMPLING_REASON_RUNTIME),
            7i32 => ::core::option::Option::Some(Self::SAMPLING_REASON_OVERRIDE),
            _ => ::core::option::Option::None,
        }
    }
    fn to_i32(&self) -> i32 {
        *self as i32
    }
    fn proto_name(&self) -> &'static str {
        match self {
            Self::SAMPLING_REASON_UNSPECIFIED => "SAMPLING_REASON_UNSPECIFIED",
            Self::SAMPLING_REASON_HEAD_RATE => "SAMPLING_REASON_HEAD_RATE",
            Self::SAMPLING_REASON_TAIL_ERROR => "SAMPLING_REASON_TAIL_ERROR",
            Self::SAMPLING_REASON_SLOW => "SAMPLING_REASON_SLOW",
            Self::SAMPLING_REASON_FORENSIC => "SAMPLING_REASON_FORENSIC",
            Self::SAMPLING_REASON_AUDIT => "SAMPLING_REASON_AUDIT",
            Self::SAMPLING_REASON_RUNTIME => "SAMPLING_REASON_RUNTIME",
            Self::SAMPLING_REASON_OVERRIDE => "SAMPLING_REASON_OVERRIDE",
        }
    }
    fn from_proto_name(name: &str) -> ::core::option::Option<Self> {
        match name {
            "SAMPLING_REASON_UNSPECIFIED" => {
                ::core::option::Option::Some(Self::SAMPLING_REASON_UNSPECIFIED)
            }
            "SAMPLING_REASON_HEAD_RATE" => {
                ::core::option::Option::Some(Self::SAMPLING_REASON_HEAD_RATE)
            }
            "SAMPLING_REASON_TAIL_ERROR" => {
                ::core::option::Option::Some(Self::SAMPLING_REASON_TAIL_ERROR)
            }
            "SAMPLING_REASON_SLOW" => {
                ::core::option::Option::Some(Self::SAMPLING_REASON_SLOW)
            }
            "SAMPLING_REASON_FORENSIC" => {
                ::core::option::Option::Some(Self::SAMPLING_REASON_FORENSIC)
            }
            "SAMPLING_REASON_AUDIT" => {
                ::core::option::Option::Some(Self::SAMPLING_REASON_AUDIT)
            }
            "SAMPLING_REASON_RUNTIME" => {
                ::core::option::Option::Some(Self::SAMPLING_REASON_RUNTIME)
            }
            "SAMPLING_REASON_OVERRIDE" => {
                ::core::option::Option::Some(Self::SAMPLING_REASON_OVERRIDE)
            }
            _ => ::core::option::Option::None,
        }
    }
    fn values() -> &'static [Self] {
        &[
            Self::SAMPLING_REASON_UNSPECIFIED,
            Self::SAMPLING_REASON_HEAD_RATE,
            Self::SAMPLING_REASON_TAIL_ERROR,
            Self::SAMPLING_REASON_SLOW,
            Self::SAMPLING_REASON_FORENSIC,
            Self::SAMPLING_REASON_AUDIT,
            Self::SAMPLING_REASON_RUNTIME,
            Self::SAMPLING_REASON_OVERRIDE,
        ]
    }
}
