// @generated by buffa-codegen. DO NOT EDIT.

include!("obs.runtime.v1.self_events.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("obs.runtime.v1.self_events.__view.rs");
        pub mod oneof {
            #[allow(unused_imports)]
            use super::*;
            include!("obs.runtime.v1.self_events.__view_oneof.rs");
        }
    }
    pub mod oneof {
        #[allow(unused_imports)]
        use super::*;
        include!("obs.runtime.v1.self_events.__oneof.rs");
    }
    pub mod ext {
        #[allow(unused_imports)]
        use super::*;
        include!("obs.runtime.v1.self_events.__ext.rs");
    }
}
