// @generated by buffa-codegen. DO NOT EDIT.
// source: obs/v1/envelope.proto

#[derive(Clone, PartialEq, Default)]
pub struct ObsEnvelope {
    /// Field 1: `full_name`
    pub full_name: ::buffa::alloc::string::String,
    /// Field 2: `schema_hash`
    pub schema_hash: u64,
    /// Field 3: `tier`
    pub tier: ::buffa::EnumValue<Tier>,
    /// Field 4: `sev`
    pub sev: ::buffa::EnumValue<Severity>,
    /// Field 5: `ts_ns`
    pub ts_ns: u64,
    /// Field 6: `trace_id`
    pub trace_id: ::buffa::alloc::string::String,
    /// Field 7: `span_id`
    pub span_id: ::buffa::alloc::string::String,
    /// Field 8: `parent_span_id`
    pub parent_span_id: ::buffa::alloc::string::String,
    /// Field 9: `service`
    pub service: ::buffa::alloc::string::String,
    /// Field 10: `instance`
    pub instance: ::buffa::alloc::string::String,
    /// Field 11: `version`
    pub version: ::buffa::alloc::string::String,
    /// Field 12: `payload`
    pub payload: ::buffa::alloc::vec::Vec<u8>,
    /// Field 13: `labels`
    pub labels: ::buffa::__private::HashMap<
        ::buffa::alloc::string::String,
        ::buffa::alloc::string::String,
    >,
    /// Field 14: `sampling_reason`
    pub sampling_reason: ::buffa::EnumValue<SamplingReason>,
    /// Field 15: `callsite_id`
    pub callsite_id: u64,
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for ObsEnvelope {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ObsEnvelope")
            .field("full_name", &self.full_name)
            .field("schema_hash", &self.schema_hash)
            .field("tier", &self.tier)
            .field("sev", &self.sev)
            .field("ts_ns", &self.ts_ns)
            .field("trace_id", &self.trace_id)
            .field("span_id", &self.span_id)
            .field("parent_span_id", &self.parent_span_id)
            .field("service", &self.service)
            .field("instance", &self.instance)
            .field("version", &self.version)
            .field("payload", &self.payload)
            .field("labels", &self.labels)
            .field("sampling_reason", &self.sampling_reason)
            .field("callsite_id", &self.callsite_id)
            .finish()
    }
}
impl ObsEnvelope {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/obs.v1.ObsEnvelope";
}
impl ::buffa::DefaultInstance for ObsEnvelope {
    fn default_instance() -> &'static Self {
        static VALUE: ::buffa::__private::OnceBox<ObsEnvelope> = ::buffa::__private::OnceBox::new();
        VALUE.get_or_init(|| ::buffa::alloc::boxed::Box::new(Self::default()))
    }
}
impl ::buffa::Message for ObsEnvelope {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.full_name.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.full_name) as u32;
        }
        if self.schema_hash != 0u64 {
            size += 1u32 + ::buffa::types::FIXED64_ENCODED_LEN as u32;
        }
        {
            let val = self.tier.to_i32();
            if val != 0 {
                size += 1u32 + ::buffa::types::int32_encoded_len(val) as u32;
            }
        }
        {
            let val = self.sev.to_i32();
            if val != 0 {
                size += 1u32 + ::buffa::types::int32_encoded_len(val) as u32;
            }
        }
        if self.ts_ns != 0u64 {
            size += 1u32 + ::buffa::types::FIXED64_ENCODED_LEN as u32;
        }
        if !self.trace_id.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.trace_id) as u32;
        }
        if !self.span_id.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.span_id) as u32;
        }
        if !self.parent_span_id.is_empty() {
            size
                += 1u32
                    + ::buffa::types::string_encoded_len(&self.parent_span_id) as u32;
        }
        if !self.service.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.service) as u32;
        }
        if !self.instance.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.instance) as u32;
        }
        if !self.version.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.version) as u32;
        }
        if !self.payload.is_empty() {
            size += 1u32 + ::buffa::types::bytes_encoded_len(&self.payload) as u32;
        }
        {
            let val = self.sampling_reason.to_i32();
            if val != 0 {
                size += 1u32 + ::buffa::types::int32_encoded_len(val) as u32;
            }
        }
        if self.callsite_id != 0u64 {
            size += 1u32 + ::buffa::types::FIXED64_ENCODED_LEN as u32;
        }
        #[allow(clippy::for_kv_map)]
        for (k, v) in &self.labels {
            let entry_size: u32 = 1u32 + ::buffa::types::string_encoded_len(k) as u32
                + 1u32 + ::buffa::types::string_encoded_len(v) as u32;
            size
                += 1u32 + ::buffa::encoding::varint_len(entry_size as u64) as u32
                    + entry_size;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.full_name.is_empty() {
            ::buffa::encoding::Tag::new(
                    1u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.full_name, buf);
        }
        if self.schema_hash != 0u64 {
            ::buffa::encoding::Tag::new(2u32, ::buffa::encoding::WireType::Fixed64)
                .encode(buf);
            ::buffa::types::encode_fixed64(self.schema_hash, buf);
        }
        {
            let val = self.tier.to_i32();
            if val != 0 {
                ::buffa::encoding::Tag::new(3u32, ::buffa::encoding::WireType::Varint)
                    .encode(buf);
                ::buffa::types::encode_int32(val, buf);
            }
        }
        {
            let val = self.sev.to_i32();
            if val != 0 {
                ::buffa::encoding::Tag::new(4u32, ::buffa::encoding::WireType::Varint)
                    .encode(buf);
                ::buffa::types::encode_int32(val, buf);
            }
        }
        if self.ts_ns != 0u64 {
            ::buffa::encoding::Tag::new(5u32, ::buffa::encoding::WireType::Fixed64)
                .encode(buf);
            ::buffa::types::encode_fixed64(self.ts_ns, buf);
        }
        if !self.trace_id.is_empty() {
            ::buffa::encoding::Tag::new(
                    6u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.trace_id, buf);
        }
        if !self.span_id.is_empty() {
            ::buffa::encoding::Tag::new(
                    7u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.span_id, buf);
        }
        if !self.parent_span_id.is_empty() {
            ::buffa::encoding::Tag::new(
                    8u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.parent_span_id, buf);
        }
        if !self.service.is_empty() {
            ::buffa::encoding::Tag::new(
                    9u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.service, buf);
        }
        if !self.instance.is_empty() {
            ::buffa::encoding::Tag::new(
                    10u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.instance, buf);
        }
        if !self.version.is_empty() {
            ::buffa::encoding::Tag::new(
                    11u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.version, buf);
        }
        if !self.payload.is_empty() {
            ::buffa::encoding::Tag::new(
                    12u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_bytes(&self.payload, buf);
        }
        {
            let val = self.sampling_reason.to_i32();
            if val != 0 {
                ::buffa::encoding::Tag::new(14u32, ::buffa::encoding::WireType::Varint)
                    .encode(buf);
                ::buffa::types::encode_int32(val, buf);
            }
        }
        if self.callsite_id != 0u64 {
            ::buffa::encoding::Tag::new(15u32, ::buffa::encoding::WireType::Fixed64)
                .encode(buf);
            ::buffa::types::encode_fixed64(self.callsite_id, buf);
        }
        for (k, v) in &self.labels {
            let entry_size: u32 = 1u32 + ::buffa::types::string_encoded_len(k) as u32
                + 1u32 + ::buffa::types::string_encoded_len(v) as u32;
            ::buffa::encoding::Tag::new(
                    13u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(entry_size as u64, buf);
            ::buffa::encoding::Tag::new(
                    1u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(k, buf);
            ::buffa::encoding::Tag::new(
                    2u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(v, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        depth: u32,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 1u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.full_name, buf)?;
            }
            2u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::Fixed64 {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 2u32,
                        expected: 1u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                self.schema_hash = ::buffa::types::decode_fixed64(buf)?;
            }
            3u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::Varint {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 3u32,
                        expected: 0u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                self.tier = ::buffa::EnumValue::from(::buffa::types::decode_int32(buf)?);
            }
            4u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::Varint {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 4u32,
                        expected: 0u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                self.sev = ::buffa::EnumValue::from(::buffa::types::decode_int32(buf)?);
            }
            5u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::Fixed64 {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 5u32,
                        expected: 1u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                self.ts_ns = ::buffa::types::decode_fixed64(buf)?;
            }
            6u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 6u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.trace_id, buf)?;
            }
            7u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 7u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.span_id, buf)?;
            }
            8u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 8u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.parent_span_id, buf)?;
            }
            9u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 9u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.service, buf)?;
            }
            10u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 10u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.instance, buf)?;
            }
            11u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 11u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.version, buf)?;
            }
            12u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 12u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_bytes(&mut self.payload, buf)?;
            }
            14u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::Varint {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 14u32,
                        expected: 0u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                self.sampling_reason = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            15u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::Fixed64 {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 15u32,
                        expected: 1u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                self.callsite_id = ::buffa::types::decode_fixed64(buf)?;
            }
            13u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 13u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                let entry_len = ::buffa::encoding::decode_varint(buf)?;
                let entry_len = usize::try_from(entry_len)
                    .map_err(|_| ::buffa::DecodeError::MessageTooLarge)?;
                if buf.remaining() < entry_len {
                    return ::core::result::Result::Err(
                        ::buffa::DecodeError::UnexpectedEof,
                    );
                }
                let entry_limit = buf.remaining() - entry_len;
                let mut key = ::core::default::Default::default();
                let mut val = ::core::default::Default::default();
                while buf.remaining() > entry_limit {
                    let entry_tag = ::buffa::encoding::Tag::decode(buf)?;
                    match entry_tag.field_number() {
                        1 => {
                            if entry_tag.wire_type()
                                != ::buffa::encoding::WireType::LengthDelimited
                            {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: entry_tag.field_number(),
                                    expected: 2u8,
                                    actual: entry_tag.wire_type() as u8,
                                });
                            }
                            key = ::buffa::types::decode_string(buf)?;
                        }
                        2 => {
                            if entry_tag.wire_type()
                                != ::buffa::encoding::WireType::LengthDelimited
                            {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: entry_tag.field_number(),
                                    expected: 2u8,
                                    actual: entry_tag.wire_type() as u8,
                                });
                            }
                            val = ::buffa::types::decode_string(buf)?;
                        }
                        _ => {
                            ::buffa::encoding::skip_field_depth(entry_tag, buf, depth)?;
                        }
                    }
                }
                if buf.remaining() != entry_limit {
                    let remaining = buf.remaining();
                    if remaining > entry_limit {
                        buf.advance(remaining - entry_limit);
                    } else {
                        return ::core::result::Result::Err(
                            ::buffa::DecodeError::UnexpectedEof,
                        );
                    }
                }
                self.labels.insert(key, val);
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, depth)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.full_name.clear();
        self.schema_hash = 0u64;
        self.tier = ::buffa::EnumValue::from(0);
        self.sev = ::buffa::EnumValue::from(0);
        self.ts_ns = 0u64;
        self.trace_id.clear();
        self.span_id.clear();
        self.parent_span_id.clear();
        self.service.clear();
        self.instance.clear();
        self.version.clear();
        self.payload.clear();
        self.sampling_reason = ::buffa::EnumValue::from(0);
        self.callsite_id = 0u64;
        self.labels.clear();
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for ObsEnvelope {
    const PROTO_FQN: &'static str = "obs.v1.ObsEnvelope";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct ObsBatch {
    /// Field 1: `format_ver`
    pub format_ver: u32,
    /// Field 2: `batch_id`
    pub batch_id: ::buffa::alloc::string::String,
    /// Field 3: `started_ns`
    pub started_ns: u64,
    /// Field 4: `closed_ns`
    pub closed_ns: u64,
    /// Field 5: `schemas`
    pub schemas: ::buffa::__private::HashMap<u64, ::buffa::alloc::string::String>,
    /// Field 6: `events`
    pub events: ::buffa::alloc::vec::Vec<ObsEnvelope>,
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for ObsBatch {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ObsBatch")
            .field("format_ver", &self.format_ver)
            .field("batch_id", &self.batch_id)
            .field("started_ns", &self.started_ns)
            .field("closed_ns", &self.closed_ns)
            .field("schemas", &self.schemas)
            .field("events", &self.events)
            .finish()
    }
}
impl ObsBatch {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/obs.v1.ObsBatch";
}
impl ::buffa::DefaultInstance for ObsBatch {
    fn default_instance() -> &'static Self {
        static VALUE: ::buffa::__private::OnceBox<ObsBatch> = ::buffa::__private::OnceBox::new();
        VALUE.get_or_init(|| ::buffa::alloc::boxed::Box::new(Self::default()))
    }
}
impl ::buffa::Message for ObsBatch {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.format_ver != 0u32 {
            size += 1u32 + ::buffa::types::uint32_encoded_len(self.format_ver) as u32;
        }
        if !self.batch_id.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.batch_id) as u32;
        }
        if self.started_ns != 0u64 {
            size += 1u32 + ::buffa::types::FIXED64_ENCODED_LEN as u32;
        }
        if self.closed_ns != 0u64 {
            size += 1u32 + ::buffa::types::FIXED64_ENCODED_LEN as u32;
        }
        for v in &self.events {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        #[allow(clippy::for_kv_map)]
        for (_k, v) in &self.schemas {
            let entry_size: u32 = 1u32 + ::buffa::types::FIXED64_ENCODED_LEN as u32
                + 1u32 + ::buffa::types::string_encoded_len(v) as u32;
            size
                += 1u32 + ::buffa::encoding::varint_len(entry_size as u64) as u32
                    + entry_size;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.format_ver != 0u32 {
            ::buffa::encoding::Tag::new(1u32, ::buffa::encoding::WireType::Varint)
                .encode(buf);
            ::buffa::types::encode_uint32(self.format_ver, buf);
        }
        if !self.batch_id.is_empty() {
            ::buffa::encoding::Tag::new(
                    2u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.batch_id, buf);
        }
        if self.started_ns != 0u64 {
            ::buffa::encoding::Tag::new(3u32, ::buffa::encoding::WireType::Fixed64)
                .encode(buf);
            ::buffa::types::encode_fixed64(self.started_ns, buf);
        }
        if self.closed_ns != 0u64 {
            ::buffa::encoding::Tag::new(4u32, ::buffa::encoding::WireType::Fixed64)
                .encode(buf);
            ::buffa::types::encode_fixed64(self.closed_ns, buf);
        }
        for v in &self.events {
            ::buffa::encoding::Tag::new(
                    6u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(__cache.consume_next() as u64, buf);
            v.write_to(__cache, buf);
        }
        for (k, v) in &self.schemas {
            let entry_size: u32 = 1u32 + ::buffa::types::FIXED64_ENCODED_LEN as u32
                + 1u32 + ::buffa::types::string_encoded_len(v) as u32;
            ::buffa::encoding::Tag::new(
                    5u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(entry_size as u64, buf);
            ::buffa::encoding::Tag::new(1u32, ::buffa::encoding::WireType::Fixed64)
                .encode(buf);
            ::buffa::types::encode_fixed64(*k, buf);
            ::buffa::encoding::Tag::new(
                    2u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(v, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        depth: u32,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::Varint {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 1u32,
                        expected: 0u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                self.format_ver = ::buffa::types::decode_uint32(buf)?;
            }
            2u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 2u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.batch_id, buf)?;
            }
            3u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::Fixed64 {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 3u32,
                        expected: 1u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                self.started_ns = ::buffa::types::decode_fixed64(buf)?;
            }
            4u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::Fixed64 {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 4u32,
                        expected: 1u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                self.closed_ns = ::buffa::types::decode_fixed64(buf)?;
            }
            6u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 6u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                let mut elem = ::core::default::Default::default();
                ::buffa::Message::merge_length_delimited(&mut elem, buf, depth)?;
                self.events.push(elem);
            }
            5u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 5u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                let entry_len = ::buffa::encoding::decode_varint(buf)?;
                let entry_len = usize::try_from(entry_len)
                    .map_err(|_| ::buffa::DecodeError::MessageTooLarge)?;
                if buf.remaining() < entry_len {
                    return ::core::result::Result::Err(
                        ::buffa::DecodeError::UnexpectedEof,
                    );
                }
                let entry_limit = buf.remaining() - entry_len;
                let mut key = ::core::default::Default::default();
                let mut val = ::core::default::Default::default();
                while buf.remaining() > entry_limit {
                    let entry_tag = ::buffa::encoding::Tag::decode(buf)?;
                    match entry_tag.field_number() {
                        1 => {
                            if entry_tag.wire_type()
                                != ::buffa::encoding::WireType::Fixed64
                            {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: entry_tag.field_number(),
                                    expected: 1u8,
                                    actual: entry_tag.wire_type() as u8,
                                });
                            }
                            key = ::buffa::types::decode_fixed64(buf)?;
                        }
                        2 => {
                            if entry_tag.wire_type()
                                != ::buffa::encoding::WireType::LengthDelimited
                            {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: entry_tag.field_number(),
                                    expected: 2u8,
                                    actual: entry_tag.wire_type() as u8,
                                });
                            }
                            val = ::buffa::types::decode_string(buf)?;
                        }
                        _ => {
                            ::buffa::encoding::skip_field_depth(entry_tag, buf, depth)?;
                        }
                    }
                }
                if buf.remaining() != entry_limit {
                    let remaining = buf.remaining();
                    if remaining > entry_limit {
                        buf.advance(remaining - entry_limit);
                    } else {
                        return ::core::result::Result::Err(
                            ::buffa::DecodeError::UnexpectedEof,
                        );
                    }
                }
                self.schemas.insert(key, val);
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, depth)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.format_ver = 0u32;
        self.batch_id.clear();
        self.started_ns = 0u64;
        self.closed_ns = 0u64;
        self.events.clear();
        self.schemas.clear();
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for ObsBatch {
    const PROTO_FQN: &'static str = "obs.v1.ObsBatch";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
