//! Build-time codegen helpers for the proto-first authoring path.
//!
//! Phase-1 surface (impl-plan task 1.10):
//!
//! - [`Config::compile`] runs `protoc` (or accepts a precompiled FDS),
//!   hands the FDS to `buffa-build` for Rust-type generation, then
//!   walks the FDS via `buffa-reflect` to extract the
//!   `(obs.v1.event)` and `(obs.v1.field)` custom options out of each
//!   message's `MessageOptions.__buffa_unknown_fields`. From those
//!   bytes the codegen emits `EventSchema` impls, `EventSchemaErased`
//!   impls, and `linkme` registrations into `OUT_DIR/obs/schemas.rs`.
//! - The byte-identical-output property described in spec 12 § 1.2
//!   (proto-first vs Rust-first land on the same generated bytes when
//!   the schemas are equivalent) is verified via Phase-2 task 2.1
//!   integration tests; Phase 1 ships the codegen, the test harness
//!   builds on top.
//!
//! See spec 12 § 4 + spec 14 § 7.

// `obs-build` runs in the user's `build.rs` (sync, before the async
// runtime exists), so the workspace's tokio-fs / no-expect lints don't
// apply here. Tests use `.unwrap()` freely.
#![allow(
    missing_docs,
    clippy::disallowed_types,
    clippy::disallowed_methods,
    clippy::expect_used,
    clippy::indexing_slicing
)]
#![cfg_attr(test, allow(clippy::unwrap_used))]

mod config;
mod options;

pub use config::{Config, DescriptorSource};
pub use options::{CodegenError, EventOptions, FieldOptions, MetricSpec};
