//! `#[derive(Event)]` expansion. Spec 12 § 1.2 + § 3.4.

use heck::ToShoutySnakeCase;
use proc_macro2::{Span, TokenStream};
use quote::{format_ident, quote};
use syn::{
    Attribute, Data, DataStruct, DeriveInput, Field, Fields, Ident, LitStr, Meta, Token, Type,
    parse2, punctuated::Punctuated,
};

pub(crate) fn expand(input: TokenStream) -> syn::Result<TokenStream> {
    let derive: DeriveInput = parse2(input)?;
    let name = derive.ident.clone();
    let vis = derive.vis.clone();

    let Data::Struct(DataStruct {
        fields: Fields::Named(named),
        ..
    }) = &derive.data
    else {
        return Err(syn::Error::new_spanned(
            &derive.ident,
            "#[derive(Event)] only supports structs with named fields",
        ));
    };

    let container = parse_container_attrs(&derive.attrs)?;
    let fields = named
        .named
        .iter()
        .map(parse_field)
        .collect::<syn::Result<Vec<_>>>()?;

    let full_name_lit = container.full_name(&name);
    let tier = container.tier_path();
    let default_sev = container.sev_path();

    let schema_hash = compute_schema_hash(&full_name_lit.value(), &container, &fields);
    let fields_const = fields_const_array(&fields);

    let project_body = project_impl(&fields);
    let encode_body = encode_payload_impl(&fields);

    let lints = lint_block(&name, &container, &fields)?;

    let schema_static_ident =
        format_ident!("__OBS_SCHEMA_{}", name.to_string().to_shouty_snake_case());
    let erased_struct_ident = format_ident!("{}Schema", name);
    let builder_ident = format_ident!("{}Builder", name);

    let setter_methods = fields.iter().map(|f| {
        let ident = &f.ident;
        let ty = &f.ty;
        quote! {
            #[doc = "Setter generated by `#[derive(Event)]`."]
            #vis fn #ident(mut self, value: impl ::std::convert::Into<#ty>) -> Self {
                self.inner.#ident = value.into();
                self
            }
        }
    });

    let out = quote! {
        impl ::obs_core::EventSchema for #name {
            const FULL_NAME: &'static str = #full_name_lit;
            const TIER: ::obs_core::__private::Tier = #tier;
            const DEFAULT_SEV: ::obs_core::__private::Severity = #default_sev;
            const FIELDS: &'static [::obs_core::FieldMeta] = &#fields_const;
            const SCHEMA_HASH: u64 = #schema_hash;

            fn encode_payload(&self, buf: &mut ::obs_core::__private::BytesMut) {
                #encode_body
            }

            fn project(&self, env: &mut ::obs_core::ObsEnvelope) {
                #project_body
            }
        }

        #[doc(hidden)]
        #[allow(non_camel_case_types)]
        #vis struct #erased_struct_ident;

        impl ::obs_core::__private::Sealed for #erased_struct_ident {}

        impl ::obs_core::__private::EventSchemaErased for #erased_struct_ident {
            fn full_name(&self) -> &'static str {
                <#name as ::obs_core::EventSchema>::FULL_NAME
            }
            fn schema_hash(&self) -> u64 {
                <#name as ::obs_core::EventSchema>::SCHEMA_HASH
            }
            fn tier(&self) -> ::obs_core::__private::Tier {
                <#name as ::obs_core::EventSchema>::TIER
            }
            fn default_sev(&self) -> ::obs_core::__private::Severity {
                <#name as ::obs_core::EventSchema>::DEFAULT_SEV
            }
            fn fields(&self) -> &'static [::obs_core::FieldMeta] {
                <#name as ::obs_core::EventSchema>::FIELDS
            }
        }

        #[used]
        #[::obs_core::__private::linkme::distributed_slice(::obs_core::__private::EVENT_SCHEMAS)]
        #[linkme(crate = ::obs_core::__private::linkme)]
        #[doc(hidden)]
        static #schema_static_ident: &'static dyn ::obs_core::__private::EventSchemaErased
            = &#erased_struct_ident;

        #lints

        #[doc = "Builder generated by `#[derive(Event)]`. Each setter takes the"]
        #[doc = "field's concrete type. Call `.emit()` to ship the event through"]
        #[doc = "`obs::observer()`."]
        #vis struct #builder_ident {
            inner: #name,
        }

        impl #builder_ident {
            #(#setter_methods)*

            /// Finalise the builder into the event struct.
            #vis fn build(self) -> #name {
                self.inner
            }

            /// Build and emit at the schema's default severity.
            #vis fn emit(self) {
                let evt = self.build();
                ::obs_core::Emit::emit(evt);
            }

            /// Build and emit at a specific severity (escalate or demote).
            #vis fn emit_at(self, sev: ::obs_core::__private::Severity) {
                let evt = self.build();
                ::obs_core::Emit::emit_at(evt, sev);
            }
        }

        impl #name {
            /// Begin building this event. Pair with field setters and `.emit()`.
            #vis fn builder() -> #builder_ident {
                #builder_ident {
                    inner: <Self as ::std::default::Default>::default(),
                }
            }
        }
    };
    Ok(out)
}

#[derive(Debug)]
struct ContainerAttrs {
    tier: String,
    default_sev: String,
    full_name: Option<String>,
}

impl ContainerAttrs {
    fn full_name(&self, ident: &Ident) -> LitStr {
        let value = self.full_name.clone().unwrap_or_else(|| ident.to_string());
        LitStr::new(&value, Span::call_site())
    }

    fn tier_path(&self) -> TokenStream {
        match self.tier.to_ascii_lowercase().as_str() {
            "log" => quote!(::obs_core::__private::Tier::Log),
            "metric" => quote!(::obs_core::__private::Tier::Metric),
            "trace" => quote!(::obs_core::__private::Tier::Trace),
            "audit" => quote!(::obs_core::__private::Tier::Audit),
            other => {
                let msg = format!("obs: unknown tier `{other}`; expected log|metric|trace|audit");
                quote!(compile_error!(#msg))
            }
        }
    }

    fn sev_path(&self) -> TokenStream {
        match self.default_sev.to_ascii_lowercase().as_str() {
            "trace" => quote!(::obs_core::__private::Severity::Trace),
            "debug" => quote!(::obs_core::__private::Severity::Debug),
            "info" => quote!(::obs_core::__private::Severity::Info),
            "warn" => quote!(::obs_core::__private::Severity::Warn),
            "error" => quote!(::obs_core::__private::Severity::Error),
            "fatal" => quote!(::obs_core::__private::Severity::Fatal),
            other => {
                let msg = format!(
                    "obs: unknown default_sev `{other}`; expected \
                     trace|debug|info|warn|error|fatal"
                );
                quote!(compile_error!(#msg))
            }
        }
    }
}

fn parse_container_attrs(attrs: &[Attribute]) -> syn::Result<ContainerAttrs> {
    let mut tier = String::from("log");
    let mut default_sev = String::from("info");
    let mut full_name: Option<String> = None;

    for attr in attrs {
        if !attr.path().is_ident("event") {
            continue;
        }
        let pairs: Punctuated<Meta, Token![,]> =
            attr.parse_args_with(Punctuated::parse_terminated)?;
        for meta in pairs {
            match meta {
                Meta::NameValue(nv) if nv.path.is_ident("tier") => {
                    tier = lit_to_string(&nv.value)?;
                }
                Meta::NameValue(nv) if nv.path.is_ident("default_sev") => {
                    default_sev = lit_to_string(&nv.value)?;
                }
                Meta::NameValue(nv) if nv.path.is_ident("full_name") => {
                    full_name = Some(lit_to_string(&nv.value)?);
                }
                other => {
                    return Err(syn::Error::new_spanned(
                        other,
                        "#[event(...)] supports tier / default_sev / full_name",
                    ));
                }
            }
        }
    }

    Ok(ContainerAttrs {
        tier,
        default_sev,
        full_name,
    })
}

struct ObsField {
    ident: Ident,
    ty: Type,
    role: String,
    cardinality: String,
    classification: String,
    proto_number: u32,
}

impl ObsField {
    fn role_token(&self) -> TokenStream {
        match self.role.as_str() {
            "label" => quote!(::obs_core::FieldRole::Label),
            "attribute" => quote!(::obs_core::FieldRole::Attribute),
            "measurement" => quote!(::obs_core::FieldRole::Measurement),
            "trace_id" => quote!(::obs_core::FieldRole::TraceId),
            "span_id" => quote!(::obs_core::FieldRole::SpanId),
            "parent_span_id" => quote!(::obs_core::FieldRole::ParentSpanId),
            "timestamp_ns" => quote!(::obs_core::FieldRole::TimestampNs),
            "duration_ns" => quote!(::obs_core::FieldRole::DurationNs),
            "forensic" => quote!(::obs_core::FieldRole::Forensic),
            _ => quote!(::obs_core::FieldRole::Attribute),
        }
    }
    fn cardinality_token(&self) -> TokenStream {
        match self.cardinality.as_str() {
            "low" => quote!(::obs_core::__private::Cardinality::Low),
            "medium" => quote!(::obs_core::__private::Cardinality::Medium),
            "high" => quote!(::obs_core::__private::Cardinality::High),
            "unbounded" => quote!(::obs_core::__private::Cardinality::Unbounded),
            _ => quote!(::obs_core::__private::Cardinality::Unspecified),
        }
    }
    fn classification_token(&self) -> TokenStream {
        match self.classification.as_str() {
            "pii" => quote!(::obs_core::__private::Classification::Pii),
            "secret" => quote!(::obs_core::__private::Classification::Secret),
            "internal" => quote!(::obs_core::__private::Classification::Internal),
            _ => quote!(::obs_core::__private::Classification::Internal),
        }
    }
}

fn parse_field(field: &Field) -> syn::Result<ObsField> {
    let ident = field
        .ident
        .clone()
        .ok_or_else(|| syn::Error::new_spanned(field, "obs: only named fields are supported"))?;
    let mut role = String::new();
    let mut cardinality = String::new();
    let mut classification = String::new();
    let mut number: u32 = 0;

    for attr in &field.attrs {
        if !attr.path().is_ident("obs") {
            continue;
        }
        let pairs: Punctuated<Meta, Token![,]> =
            attr.parse_args_with(Punctuated::parse_terminated)?;
        for meta in pairs {
            match meta {
                Meta::Path(p) => {
                    role = p.get_ident().map(Ident::to_string).unwrap_or_default();
                }
                Meta::NameValue(nv) if nv.path.is_ident("cardinality") => {
                    cardinality = lit_to_string(&nv.value)?;
                }
                Meta::NameValue(nv) if nv.path.is_ident("classification") => {
                    classification = lit_to_string(&nv.value)?;
                }
                Meta::NameValue(nv) if nv.path.is_ident("number") => {
                    number = lit_to_string(&nv.value)?
                        .parse::<u32>()
                        .map_err(|e| syn::Error::new_spanned(nv, format!("invalid number: {e}")))?;
                }
                other => {
                    return Err(syn::Error::new_spanned(
                        other,
                        "#[obs(...)] supports the role keyword (label|attribute|measurement|trace_id|span_id|parent_span_id|timestamp_ns|duration_ns|forensic) plus cardinality / classification / number",
                    ));
                }
            }
        }
    }

    Ok(ObsField {
        ident,
        ty: field.ty.clone(),
        role,
        cardinality,
        classification,
        proto_number: number,
    })
}

fn lit_to_string(expr: &syn::Expr) -> syn::Result<String> {
    if let syn::Expr::Lit(syn::ExprLit {
        lit: syn::Lit::Str(s),
        ..
    }) = expr
    {
        return Ok(s.value());
    }
    if let syn::Expr::Lit(syn::ExprLit {
        lit: syn::Lit::Int(i),
        ..
    }) = expr
    {
        return Ok(i.base10_digits().to_string());
    }
    Err(syn::Error::new_spanned(expr, "expected string literal"))
}

fn fields_const_array(fields: &[ObsField]) -> TokenStream {
    let entries = fields.iter().enumerate().map(|(i, f)| {
        let name_lit = LitStr::new(&f.ident.to_string(), Span::call_site());
        let role = f.role_token();
        let card = f.cardinality_token();
        let classn = f.classification_token();
        let number: u32 = if f.proto_number == 0 {
            (i as u32) + 1
        } else {
            f.proto_number
        };
        quote! {
            ::obs_core::FieldMeta::new(
                #name_lit,
                #number,
                #role,
                #card,
                #classn,
            )
        }
    });
    quote!([#(#entries),*])
}

fn project_impl(fields: &[ObsField]) -> TokenStream {
    let mut stmts: Vec<TokenStream> = Vec::new();
    for f in fields {
        let ident = &f.ident;
        let name = LitStr::new(&ident.to_string(), Span::call_site());
        match f.role.as_str() {
            "label" => stmts.push(quote! {
                {
                    let v = ::std::string::ToString::to_string(&self.#ident);
                    env.labels.insert(#name.to_string(), v);
                }
            }),
            "trace_id" => stmts.push(quote! {
                env.trace_id = ::std::string::ToString::to_string(&self.#ident);
            }),
            "span_id" => stmts.push(quote! {
                env.span_id = ::std::string::ToString::to_string(&self.#ident);
            }),
            "parent_span_id" => stmts.push(quote! {
                env.parent_span_id = ::std::string::ToString::to_string(&self.#ident);
            }),
            _ => {}
        }
    }
    quote! { #(#stmts)* }
}

fn encode_payload_impl(fields: &[ObsField]) -> TokenStream {
    // Phase-1 simplification: serialize the named fields as JSON
    // bytes. Real buffa encoding lands in Phase 2 task 2.1. The
    // JSON form is good enough for stdout and in-memory sinks; OTLP
    // and analytics sinks are not on Phase-1's path.
    let entries = fields.iter().map(|f| {
        let ident = &f.ident;
        let name = LitStr::new(&ident.to_string(), Span::call_site());
        quote! { (#name, ::std::string::ToString::to_string(&self.#ident)) }
    });
    quote! {
        let pairs: &[(&'static str, ::std::string::String)] = &[#(#entries),*];
        let mut map = ::std::collections::BTreeMap::<&'static str, ::std::string::String>::new();
        for (k, v) in pairs.iter().cloned() {
            map.insert(k, v);
        }
        if let ::std::result::Result::Ok(s) =
            ::obs_core::__private::serde_json::to_string(&map)
        {
            buf.extend_from_slice(s.as_bytes());
        }
    }
}

fn lint_block(
    name: &Ident,
    container: &ContainerAttrs,
    fields: &[ObsField],
) -> syn::Result<TokenStream> {
    let mut asserts = Vec::new();

    // L011: name starts with `Obs`.
    let n_str = name.to_string();
    if !n_str.starts_with("Obs") {
        let msg = format!(
            "obs L011: event type name `{n_str}` must start with `Obs` (default workspace prefix)"
        );
        asserts.push(quote! {
            const _: () = ::std::panic!(#msg);
        });
    }

    // L001: every LABEL field's cardinality must be Low or Medium.
    for f in fields {
        if f.role == "label" {
            let card = f.cardinality_token();
            let msg = format!(
                "obs L001: field `{name}` is LABEL but cardinality is High/Unbounded",
                name = f.ident
            );
            asserts.push(quote! {
                const _: () = ::std::assert!(#card.is_label_compatible(), #msg);
            });
        }
    }

    // L002: PII classification must not be on LABEL fields.
    for f in fields {
        if f.role == "label" && f.classification == "pii" {
            let msg = format!(
                "obs L002: field `{name}` is LABEL but classification is PII",
                name = f.ident
            );
            asserts.push(quote! {
                const _: () = ::std::panic!(#msg);
            });
        }
    }

    // L003: SECRET classification must not appear on LOG/AUDIT tier events.
    let tier_lower = container.tier.to_ascii_lowercase();
    if matches!(tier_lower.as_str(), "log" | "audit") {
        for f in fields {
            if f.classification == "secret" {
                let msg = format!(
                    "obs L003: field `{name}` is SECRET but tier is `{tier}`",
                    name = f.ident,
                    tier = container.tier
                );
                asserts.push(quote! {
                    const _: () = ::std::panic!(#msg);
                });
            }
        }
    }

    Ok(quote! { #(#asserts)* })
}

fn compute_schema_hash(full_name: &str, container: &ContainerAttrs, fields: &[ObsField]) -> u64 {
    // BLAKE3 over a stable canonical descriptor string. The first 8
    // bytes (little-endian) become `SCHEMA_HASH`. Spec 10 § 6 + spec
    // 12 § 3.5.
    let mut s = String::new();
    s.push_str(full_name);
    s.push('|');
    s.push_str(&container.tier);
    s.push('|');
    s.push_str(&container.default_sev);
    s.push('|');
    for f in fields {
        s.push_str(&f.ident.to_string());
        s.push(':');
        s.push_str(&f.role);
        s.push(':');
        s.push_str(&f.cardinality);
        s.push(':');
        s.push_str(&f.classification);
        s.push(',');
    }
    let h = blake3::hash(s.as_bytes());
    let bytes = h.as_bytes();
    let arr = <[u8; 8]>::try_from(&bytes[..8]).expect("blake3 always produces 32 bytes");
    u64::from_le_bytes(arr)
}
