#![forbid(unsafe_code)]
#![warn(rust_2024_compatibility, missing_docs, missing_debug_implementations)]

//! Façade crate — re-exports the everyday obs API.
//!
//! Most downstream apps depend only on `obs-sdk`. Spec 61 § 2.11.
//!
//! Phase-1 features:
//!
//! | Feature | Default | Pulls in |
//! | --- | --- | --- |
//! | `dev` | yes | `StdoutSink` (Phase 1 only `FormatterStyle::Full`); `StandardObserver::dev()` |
//! | `panic-hook` | yes | reserved; full impl in Phase 3 task 3.11 |
//! | `test` | no | `InMemoryObserver`, `with_test_observer` |
//!
//! Sinks (`otel`, `parquet`, `clickhouse`, `tower`,
//! `tracing-bridge`) are Phase-3+ features and are *not* exposed
//! here yet — adding them later does not break the Phase-1 surface.

pub use obs_core::{
    Cardinality, Classification, Emit, EventSchema, EventsConfig, FieldKind, FieldMeta, FieldRole,
    InMemoryHandle, InMemoryObserver, InMemorySink, MetricKind, NoopObserver, NoopSink,
    ObsBatch, ObsCallsite, ObsEnvelope, Observer, SamplingConfig, SamplingReason, Severity, Sink,
    StandardObserver, StandardObserverBuilder, StdoutSink, Tier, install_observer, observer,
    observer_weak, with_observer_thread_local, with_test_observer,
};

pub use obs_macros::{Event, emit};

#[cfg(feature = "dev")]
pub use obs_core::sink::FormatterStyle;

/// Severity ident shortcuts for use with `obs::emit!`. The macro form
/// accepts either `Severity::Warn` or the bare `WARN` ident.
pub use obs_core::Severity::{
    Debug as DEBUG, Error as ERROR, Fatal as FATAL, Info as INFO, Trace as TRACE, Warn as WARN,
};

/// Re-exports for code generated by `#[derive(Event)]` and `obs-build`.
/// Users do not depend on these directly.
#[doc(hidden)]
pub use obs_core::__private;
