// Tests routinely use `.unwrap()` for clarity; production code uses `?`.
#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used))]

//! Runtime engine for the obs SDK — the spine that user code emits into.
//!
//! Phase-1 surface (specs/91-impl-plan.md tasks 1.4–1.8):
//!
//! - [`callsite`] — `ObsCallsite`, atomic-`Interest` cache (spec 11 § 2).
//! - [`observer`] — three-tier resolution (per-task → per-thread → global)
//!   with `OVERRIDE_COUNT` fast flag and `CAN_ENTER` re-entry guard
//!   (spec 11 § 3); `Observer` trait; `NoopObserver`, `InMemoryObserver`,
//!   single-tier `StandardObserver`.
//! - [`registry`] — `EventSchemaErased` object-safe trait, the
//!   `linkme`-collected `EVENT_SCHEMAS` distributed slice, the runtime
//!   `SchemaRegistry`, `ScrubbedEnvelope` worker handoff (spec 14).
//! - [`envelope`] — envelope builder + projection helpers (spec 11 § 5).
//! - [`sink`] — `Sink` trait (`deliver(ScrubbedEnvelope<'_>)`),
//!   `NoopSink`, `InMemorySink`, `StdoutSink` w/ `FormatterStyle::Full`
//!   (specs/14 § 5, 20 § 3.6).
//! - [`config`] — `EventsConfig` shell with `ArcSwap` reload hook (spec 15).
//!
//! What's deliberately not wired yet (deferred to Phase 3 task 3.*):
//! per-tier mpsc workers, the head/tail samplers, `obs::scope!` macros
//! (the support types live here; the macros live in `obs-macros`),
//! the AUDIT spool, file-watcher reload, panic hook.

pub mod callsite;
pub mod config;
pub mod emit;
pub mod envelope;
pub mod observer;
pub mod registry;
pub mod sink;

pub use callsite::ObsCallsite;
pub use config::{EventsConfig, SamplingConfig};
pub use emit::Emit;
pub use envelope::{Envelope, EventSchema, FieldMeta, FieldRole};
pub use observer::{
    InMemoryHandle, InMemoryObserver, NoopObserver, Observer, StandardObserver,
    StandardObserverBuilder, ThreadObserverGuard, WeakObserver, install_observer, observer,
    observer_weak, with_observer_thread_local, with_test_observer,
};
pub use obs_proto::obs::v1::{ObsBatch, ObsEnvelope};
pub use obs_types::{
    Cardinality, Classification, FieldKind, MetricKind, SamplingReason, Severity, Tier,
};
pub use registry::{
    DecodeError, EVENT_SCHEMAS, EventSchemaErased, ScrubError, ScrubbedEnvelope, SchemaRegistry,
};
pub use sink::{InMemorySink, NoopSink, Sink, StdoutSink};

/// Re-exports for code generated by `obs-macros::derive(Event)` and
/// `obs-build`. End users should not depend on these directly.
#[doc(hidden)]
pub mod __private {
    pub use bytes::BytesMut;
    pub use linkme;
    pub use obs_proto::__private::*;
    pub use obs_types::*;
    pub use serde_json;

    pub use crate::callsite::ObsCallsite;
    pub use crate::registry::{EVENT_SCHEMAS, EventSchemaErased, Sealed};
}
