#![forbid(unsafe_code)]
#![warn(rust_2024_compatibility, missing_docs, missing_debug_implementations)]
// Tests routinely use `.unwrap()` for clarity; production code uses `?`.
#![cfg_attr(
    test,
    allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
        clippy::indexing_slicing
    )
)]

//! Runtime engine for the obs SDK — the spine that user code emits into.
//!
//! Phase-3 surface (specs/91-impl-plan.md tasks 3.1–3.15):
//!
//! - [`callsite`] — `ObsCallsite`, atomic-`Interest` cache (spec 11 § 2).
//! - [`observer`][mod@observer] — three-tier resolution + per-tier worker pool + `StandardObserver`
//!   (spec 11 §§ 3, 4 + 6.4).
//! - [`registry`] — schema registry + `ScrubbedEnvelope` (spec 14).
//! - [`envelope`] — envelope builder + projection helpers (spec 11 § 5).
//! - [`scope`] — `obs::scope!` / `obs::context!` runtime support (spec 13 §§ 2, 3, 6).
//! - [`instrumented`] — `Instrumented<F>` future adapter and `Instrument` / `WithObserver` traits
//!   (spec 13 § 3).
//! - [`sampling`] — head sampler (spec 13 § 6).
//! - [`filter`] — EnvFilter-shaped `obs::Filter` (spec 13 § 7).
//! - [`audit_spool`] — AUDIT-tier disk spool (spec 11 § 6.4).
//! - [`panic_hook`] — `install_panic_hook` (spec 11 § 6.1).
//! - [`span_trace`] — `obs::SpanTrace` (spec 13 § 9).
//! - [`sink`] — sink trait + writers (spec 20).

pub mod audit_spool;
pub mod aux;
pub mod callsite;
pub mod config;
pub mod config_watcher;
pub mod emit;
pub mod envelope;
pub mod filter;
pub mod forensic;
pub mod instrumented;
pub mod metric;
pub mod observer;
pub mod panic_hook;
pub mod registry;
pub mod sampling;
pub mod scope;
pub(crate) mod self_events;
pub mod sink;
pub mod span_trace;
#[cfg(feature = "test")]
pub mod test;
pub mod wire;

pub use aux::{BuildableTo, EnumCount, FieldCapture, SpanCtx, SpanFrame};
pub use callsite::ObsCallsite;
pub use config::{EventsConfig, SamplingConfig};
pub use config_watcher::{ConfigWatcher, DEFAULT_DEBOUNCE};
pub use emit::Emit;
pub use envelope::{Envelope, EventSchema, FieldMeta, FieldRole};
pub use filter::Filter;
pub use instrumented::{Instrument, Instrumented, WithObserver};
pub use metric::{MetricEmitter, NoopMetricEmitter};
pub use obs_proto::{
    ENVELOPE_FORMAT_VER,
    obs::v1::{ObsBatch, ObsEnvelope},
};
pub use obs_types::{
    Cardinality, Classification, FieldKind, MetricKind, SamplingReason, Severity, Tier,
};
pub use observer::{
    InMemoryHandle, InMemoryObserver, NoopObserver, Observer, StandardObserver,
    StandardObserverBuilder, ThreadObserverGuard, WeakObserver, WorkerCounters, install_observer,
    observer, observer_weak, with_observer_task, with_observer_task_sync,
    with_observer_thread_local, with_test_observer,
};
pub use panic_hook::install_panic_hook;
pub use registry::{
    ArrowEventSchema, ArrowField, ArrowLeafType, ArrowSchemaModel, ArrowStructBuilder,
    CallsiteRecord, CallsiteSource, DecodeError, ENVELOPE_COLUMNS, EVENT_SCHEMAS,
    EventSchemaErased, ObsCallsiteRegistry, OtelAttributeView, OtlpValue, SchemaRegistry,
    ScrubError, ScrubbedEnvelope, callsite_id, scrub_payload,
};
pub use sampling::{SamplingDecision, decide as sample_decide};
pub use scope::{ScopeField, ScopeFrame, ScopeGuard, ScopeKind};
pub use sink::{
    FormatterStyle, InMemorySink, LevelSplitWriter, MakeWriter, NdjsonFileSink, NonBlockingWriter,
    NoopSink, RollingFileWriter, RollingFileWriterBuilder, RollingPolicy, Sink, StderrWriter,
    StdoutSink, StdoutWriter, TeeWriter, WorkerGuard,
};
pub use span_trace::SpanTrace;

/// Re-exports for code generated by `obs-macros::derive(Event)` and
/// `obs-build`. End users should not depend on these directly.
#[doc(hidden)]
pub mod __private {
    pub use std::sync::OnceLock;

    pub use buffa;
    pub use bytes::BytesMut;
    pub use linkme;
    /// Proto Tier enum re-export so macros can reach it through the
    /// `__private` namespace without forcing user code to depend on
    /// `obs-proto` directly.
    pub use obs_proto::obs::v1::Severity as ProtoSeverity;
    pub use obs_proto::{
        __private::*,
        obs::v1::{SamplingReason as ProtoSamplingReason, Tier as ProtoTier},
    };
    pub use obs_types::*;
    pub use secrecy;
    pub use serde_json;

    pub use crate::{
        aux::{BuildableTo, EnumCount, FieldCapture, SpanCtx, SpanFrame},
        callsite::ObsCallsite,
        forensic::{ForensicLimiter, ensure_limiter, try_acquire_forensic},
        registry::{EVENT_SCHEMAS, EventSchemaErased, Sealed},
        scope::{ScopeField, ScopeGuard, ScopeKind},
        wire::BuffaEncodeField,
    };

    /// L011 helper: const-time test that a string starts with a known
    /// prefix.
    #[must_use]
    #[allow(clippy::indexing_slicing)]
    pub const fn starts_with_obs(name: &str, prefix: &str) -> bool {
        let n = name.as_bytes();
        let p = prefix.as_bytes();
        if n.len() < p.len() {
            return false;
        }
        let mut i = 0;
        while i < p.len() {
            if n[i] != p[i] {
                return false;
            }
            i += 1;
        }
        true
    }
}
